export type Service = {
  id: string
  name: string
  slug: string
  shortDescription: string
  longDescription: string
  icon: string
  featured: boolean
  category: 'emergency' | 'residential' | 'commercial' | 'construction' | 'remodel' | 'water-heater' | 'repair' | 'general'
}

export const SERVICES: Service[] = [
  {
    id: 'new-construction',
    name: 'New Construction Plumbing',
    slug: 'new-construction-plumbing',
    shortDescription: 'Expert plumbing installation for new residential and commercial construction projects across the Mississippi Gulf Coast.',
    longDescription: 'Prestige Plumbing LLC partners with general contractors, builders, and developers to provide full-system plumbing installation for new residential and commercial builds. We coordinate with your schedule and deliver clean, code-compliant work from rough-in to finish — on time, every time.',
    icon: 'construction',
    featured: true,
    category: 'construction',
  },
  {
    id: 'remodels',
    name: 'Plumbing Remodels',
    slug: 'plumbing-remodels',
    shortDescription: 'Kitchen and bathroom remodel plumbing handled with precision — from relocating lines to installing new fixtures.',
    longDescription: 'Planning a bathroom or kitchen remodel on the Gulf Coast? Our team handles every plumbing aspect of your renovation: relocating supply and drain lines, installing new fixtures, and making sure everything meets code so your project stays on schedule.',
    icon: 'wrench',
    featured: true,
    category: 'remodel',
  },
  {
    id: 'emergency',
    name: 'Emergency Plumbing',
    slug: 'emergency-plumbing',
    shortDescription: 'Fast, reliable 24/7 emergency plumbing for burst pipes, sewage backups, flooding, and any plumbing crisis that can\'t wait.',
    longDescription: 'Plumbing emergencies do not wait for business hours. Prestige Plumbing LLC responds 24 hours a day, 7 days a week to burst pipes, major leaks, sewer backups, water heater failures, and any urgent plumbing situation across the Mississippi Gulf Coast. Call now.',
    icon: 'alert',
    featured: true,
    category: 'emergency',
  },
  {
    id: 'commercial',
    name: 'Commercial Plumbing',
    slug: 'commercial-plumbing',
    shortDescription: 'Dependable commercial plumbing for businesses, restaurants, property managers, and contractors — residential and commercial.',
    longDescription: 'We understand that downtime is costly for businesses. Our commercial plumbing team delivers efficient, code-compliant plumbing services for offices, retail spaces, restaurants, multi-family properties, and more. We handle it all, start to finish.',
    icon: 'building',
    featured: true,
    category: 'commercial',
  },
  {
    id: 'water-heaters',
    name: 'Water Heater Services',
    slug: 'water-heater-services',
    shortDescription: 'Water heater repair and installation for tank and tankless units — fast, honest, and done right the first time.',
    longDescription: 'We repair and replace traditional tank water heaters and tankless units across the Mississippi Gulf Coast. Whether your unit is leaking, failing to heat, or simply aging out, our team assesses the situation and recommends the right solution with upfront pricing.',
    icon: 'flame',
    featured: true,
    category: 'water-heater',
  },
  {
    id: 'residential',
    name: 'Residential Plumbing',
    slug: 'residential-plumbing',
    shortDescription: 'Full-service residential plumbing for homeowners — repairs, installations, and everything in between.',
    longDescription: 'From routine repairs to complete plumbing system installations, we handle all residential plumbing needs with the care and cleanliness your home deserves. Our team works professionally inside your home, every time.',
    icon: 'home',
    featured: true,
    category: 'residential',
  },
  {
    id: 'repairs',
    name: 'Plumbing Repairs',
    slug: 'plumbing-repairs',
    shortDescription: 'Fast, honest plumbing repairs for leaks, fixtures, pipes, drains, and more.',
    longDescription: 'From minor drips to significant leaks, our plumbing repair services cover the full range of common plumbing issues. We diagnose the problem accurately and fix it right the first time.',
    icon: 'tool',
    featured: false,
    category: 'repair',
  },
  {
    id: 'installation',
    name: 'Plumbing Installation',
    slug: 'plumbing-installation',
    shortDescription: 'Professional installation of fixtures, appliances, and plumbing systems.',
    longDescription: 'We install sinks, toilets, faucets, showers, bathtubs, dishwashers, garbage disposals, and all types of plumbing fixtures and appliances. Our installations are done cleanly and to code.',
    icon: 'wrench',
    featured: false,
    category: 'general',
  },
  {
    id: 'maintenance',
    name: 'Plumbing Maintenance',
    slug: 'plumbing-maintenance',
    shortDescription: 'Proactive plumbing maintenance to catch problems before they become costly repairs.',
    longDescription: 'Regular plumbing maintenance can extend the life of your system and prevent unexpected failures. We offer inspections and maintenance services for both residential and commercial properties.',
    icon: 'shield',
    featured: false,
    category: 'general',
  },
  {
    id: 'inspections',
    name: 'Plumbing Inspections',
    slug: 'plumbing-inspections',
    shortDescription: 'Thorough plumbing inspections for home buyers, sellers, and property owners.',
    longDescription: "Our plumbing inspections provide a clear picture of your system's current condition, identifying any issues that need attention. Ideal for real estate transactions, older homes, and commercial properties.",
    icon: 'search',
    featured: false,
    category: 'general',
  },
  {
    id: 'bathroom',
    name: 'Bathroom Plumbing',
    slug: 'bathroom-plumbing',
    shortDescription: 'Complete bathroom plumbing services including installation, repair, and remodeling.',
    longDescription: 'From toilet repairs to full bathroom renovations, we handle all aspects of bathroom plumbing. Our team works with your designer or contractor to ensure all plumbing elements are installed correctly and efficiently.',
    icon: 'droplet',
    featured: false,
    category: 'residential',
  },
  {
    id: 'kitchen',
    name: 'Kitchen Plumbing',
    slug: 'kitchen-plumbing',
    shortDescription: 'Kitchen plumbing services including sink installation, garbage disposals, and dishwasher lines.',
    longDescription: 'Kitchen plumbing requires precision and experience. We install and repair kitchen sinks, faucets, garbage disposals, dishwasher connections, pot fillers, and all kitchen plumbing components.',
    icon: 'droplet',
    featured: false,
    category: 'residential',
  },
  {
    id: 'water-heater-repair',
    name: 'Water Heater Repair',
    slug: 'water-heater-repair',
    shortDescription: 'Experienced water heater repair for all makes and models.',
    longDescription: 'Not getting hot water? We diagnose and repair water heater issues including pilot light problems, thermostat failures, element replacement, and more. We work on all standard tank and tankless units.',
    icon: 'flame',
    featured: false,
    category: 'water-heater',
  },
  {
    id: 'water-heater-install',
    name: 'Water Heater Installation',
    slug: 'water-heater-installation',
    shortDescription: 'Professional water heater installation with proper permits and code compliance.',
    longDescription: 'When it is time to replace your water heater, we handle the full installation including removal of the old unit, proper permitting where required, and complete code-compliant installation of your new unit.',
    icon: 'flame',
    featured: false,
    category: 'water-heater',
  },
  {
    id: 'fixtures',
    name: 'Fixture Installation & Replacement',
    slug: 'fixture-installation',
    shortDescription: 'Expert installation and replacement of all plumbing fixtures.',
    longDescription: 'We install and replace toilets, sinks, faucets, showers, bathtubs, and all types of plumbing fixtures. Whether you are upgrading for aesthetics or replacing a failing fixture, we get it done right.',
    icon: 'wrench',
    featured: false,
    category: 'general',
  },
  {
    id: 'pipe-repair',
    name: 'Pipe Repair',
    slug: 'pipe-repair',
    shortDescription: 'Pipe repair and replacement for leaks, cracks, and damaged plumbing lines.',
    longDescription: 'Damaged or deteriorating pipes can cause serious water damage if not addressed quickly. We repair and replace all types of plumbing pipes including copper, PVC, and PEX in both residential and commercial settings.',
    icon: 'tool',
    featured: false,
    category: 'repair',
  },
  {
    id: 'leak-detection',
    name: 'Leak Detection & Repair',
    slug: 'leak-detection',
    shortDescription: 'Professional leak detection to locate hidden leaks and prevent water damage.',
    longDescription: 'Hidden leaks can cause serious structural damage over time. Our team uses proven methods to locate leaks behind walls, under slabs, and throughout your plumbing system, then we fix them efficiently.',
    icon: 'search',
    featured: false,
    category: 'repair',
  },
  {
    id: 'drain-sewer',
    name: 'Drain & Sewer Plumbing',
    slug: 'drain-sewer-plumbing',
    shortDescription: 'Drain cleaning, sewer line repair, and related plumbing services.',
    longDescription: 'Slow drains and sewer line issues can disrupt your home or business. We provide drain cleaning, sewer line inspection, and repair services to keep your drainage system flowing properly.',
    icon: 'pipe',
    featured: false,
    category: 'repair',
  },
  {
    id: 'system-replacements',
    name: 'Plumbing System Replacements',
    slug: 'plumbing-system-replacements',
    shortDescription: 'Complete plumbing system replacement for older homes and commercial buildings.',
    longDescription: 'Older properties with aging or deteriorated plumbing systems may need a complete repiping or system replacement. We assess your existing system and provide a straightforward plan to bring your plumbing up to current standards.',
    icon: 'refresh',
    featured: false,
    category: 'general',
  },
  {
    id: 'general-service',
    name: 'General Service Plumbing',
    slug: 'general-service-plumbing',
    shortDescription: 'General plumbing service for any residential or commercial plumbing need.',
    longDescription: 'Not sure which category your plumbing need falls under? No problem. Contact Prestige Plumbing LLC and describe your situation. We handle a wide range of plumbing service calls throughout the Mississippi Gulf Coast.',
    icon: 'tool',
    featured: false,
    category: 'general',
  },
]

export const FEATURED_SERVICES = SERVICES.filter((s) => s.featured)

export const SERVICE_CATEGORIES = [
  { id: 'emergency', label: 'Emergency Plumbing', href: '#emergency' },
  { id: 'residential', label: 'Residential Plumbing', href: '#residential' },
  { id: 'commercial', label: 'Commercial Plumbing', href: '#commercial' },
  { id: 'construction', label: 'New Construction', href: '#new-construction' },
  { id: 'remodel', label: 'Remodeling', href: '#remodels' },
  { id: 'water-heater', label: 'Water Heaters', href: '#water-heaters' },
  { id: 'repair', label: 'Repairs & More', href: '#repairs' },
] as const
